<li class="mainlevel" onmouseout="this.className=&#39;mainlevel&#39;" onmouseover="this.className=&#39;mainlevel1&#39;" id="mainlevel_0{dede:global name=itemindex runphp='yes'}@me=@me+1;{/dede:global}"><a href="{dede:field name='typeurl'/}">{dede:field name='typename'/}</a>
      <ul style="display: none;">
	  {dede:channel type='son'}
        <li><a href="[field:typelink/]">[field:typename/]</a></li>
	  {/dede:channel}	
      </ul>
    </li>