<?php
$z[0]=Array("channel"," <a href=\"[field:typeurl/]\">[field:typename/]</a> ",40,130);
$z[0][4]['type']="top";
$z[1]=Array("global","",149,171);
$z[1][4]['name']="cfg_add";
$z[2]=Array("global","",183,205);
$z[2][4]['name']="cfg_tel";
$z[3]=Array("global","",207,231);
$z[3][4]['name']="cfg_beian";
$z[4]=Array("global","",242,268);
$z[4][4]['name']="cfg_powerby";
$z[5]=Array("global","",539,570);
$z[5][4]['name']="cfg_cfg_basehost";

?>