<?php
$z[0]=Array("global","",56,82);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",345,366);
$z[1][4]['name']="cfg_qq";
$z[2]=Array("global","",444,465);
$z[2][4]['name']="cfg_qq";
$z[3]=Array("global","",626,648);
$z[3][4]['name']="cfg_tel";
$z[4]=Array("channelartlist","\r\n    <li class=\"mainlevel\" onmouseout=\"this.className='mainlevel'\" onmouseover=\"this.className='mainlevel1'\" id=\"mainlevel_0{dede:global name=itemindex runphp='yes'}@me=@me+1;{/dede:global}\"><a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a>\r\n      <ul style=\"display: none;\">\r\n	  {dede:channel type='son'}\r\n        <!--<li><a href=\"[field:typelink/]\">[field:typename/]</a></li>-->\r\n	  {/dede:channel}	\r\n      </ul>\r\n    </li>\r\n	\r\n	",884,1396);
$z[4][4]['typeid']="top";

?>