<?php
$z[0]=Array("global","",253,279);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",323,353);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",390,417);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",1621,1656);
$z[3][4]['filename']="head.htm";
$z[4]=Array("arclist","\r\n      <dl>\r\n        <dt><a href=\"[field:arcurl /]\"> <img src=\"[field:picname/]\" width=\"250\" height=\"189\"/></a>\r\n          <p>[field:title /]</p>\r\n        </dt>\r\n        <dd>\r\n          <p><a href=\"[field:arcurl /]\">[field:infos /]...</a></p>\r\n        </dd>\r\n      </dl>\r\n      ",3484,3857);
$z[4][4]['row']="4";
$z[4][4]['typeid']="10";
$z[4][4]['titlelen']="15";
$z[4][4]['infolen']="99";
$z[4][4]['orderby']="pubdate";
$z[5]=Array("arclist","\r\n      <li><a href=\"[field:arcurl /]\"><img src=\"[field:picname/]\">\r\n        <h4>[field:title /]</h4>\r\n        </a></li>\r\n      ",4106,4314);
$z[5][4]['row']="8";
$z[5][4]['typeid']="8";
$z[5][4]['titlelen']="15";
$z[5][4]['orderby']="pubdate";
$z[6]=Array("arclist","\r\n        <li><a href=\"[field:arcurl /]\" title=\"[field:title /]\">[field:title /]</a></li>\r\n        ",4537,4716);
$z[6][4]['row']="6";
$z[6][4]['typeid']="9";
$z[6][4]['titlelen']="40";
$z[6][4]['orderby']="pubdate";
$z[7]=Array("include","",5100,5137);
$z[7][4]['filename']="footer.htm";

?>