<?php
$z[0]=Array("global","",249,275);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",318,348);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",384,411);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",1593,1628);
$z[3][4]['filename']="head.htm";
$z[4]=Array("arclist","\n      <li><a href=\"[field:arcurl /]\"><img src=\"[field:picname/]\">\n        <h4>[field:title /]</h4>\n        </a></li>\n      ",3390,3594);
$z[4][4]['row']="8";
$z[4][4]['typeid']="8";
$z[4][4]['titlelen']="15";
$z[4][4]['orderby']="pubdate";
$z[5]=Array("arclist","\n      <dl>\n        <dt><a href=\"[field:arcurl /]\"> <img src=\"[field:picname/]\" width=\"250\" height=\"189\"/></a>\n          <p>[field:title /]</p>\n        </dt>\n        <dd>\n          <p><a href=\"[field:arcurl /]\">[field:infos /]...</a></p>\n        </dd>\n      </dl>\n      ",3890,4254);
$z[5][4]['row']="4";
$z[5][4]['typeid']="10";
$z[5][4]['titlelen']="15";
$z[5][4]['infolen']="99";
$z[5][4]['orderby']="pubdate";
$z[6]=Array("arclist","\n        <li><a href=\"[field:arcurl /]\" title=\"[field:title /]\">[field:title /]</a></li>\n        ",4451,4628);
$z[6][4]['row']="6";
$z[6][4]['typeid']="9";
$z[6][4]['titlelen']="40";
$z[6][4]['orderby']="pubdate";
$z[7]=Array("include","",4998,5035);
$z[7][4]['filename']="footer.htm";

?>