<?php
$z[0]=Array("field","",249,268);
$z[0][4]['name']="title";
$z[1]=Array("global","",269,295);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1283,1318);
$z[2][4]['filename']="head.htm";
$z[3]=Array("field","",1371,1390);
$z[3][4]['name']="title";
$z[4]=Array("include","",1584,1619);
$z[4][4]['filename']="left.htm";
$z[5]=Array("field","",1683,1712);
$z[5][4]['name']="position";
$z[6]=Array("field","",1723,1752);
$z[6][4]['name']="typename";
$z[7]=Array("list","\n        <li><a href=\"[field:arcurl/]\"><img src=\"[field:picname/]\"></a>\n          <h4><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></h4>\n          <span>文章来源：<b>[field:adminname/]</b> 上传时间：<b>[field:pubdate function=\"GetDateTimeMK(@me)\" /]</b> 阅览次数：<b>[field:click/]</b></span>\n          <p>[field:infos/]...<a href=\"[field:arcurl/]\">【详细】</a></p>\n        </li>\n        ",1818,2278);
$z[7][4]['pagesize']="4";
$z[7][4]['infolen']="180";
$z[8]=Array("pagelist","",2348,2411);
$z[8][4]['listitem']="index,info,next,pageno";
$z[8][4]['listsize']="5";
$z[9]=Array("include","",2492,2529);
$z[9][4]['filename']="footer.htm";

?>