<?php
$z[0]=Array("field","",253,272);
$z[0][4]['name']="title";
$z[1]=Array("global","",273,299);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",340,369);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",409,467);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1304,1339);
$z[4][4]['filename']="head.htm";
$z[5]=Array("include","",1552,1587);
$z[5][4]['filename']="left.htm";
$z[6]=Array("field","",1653,1682);
$z[6][4]['name']="position";
$z[7]=Array("field","",1693,1722);
$z[7][4]['name']="typename";
$z[8]=Array("list","\r\n        <li><a href=\"[field:arcurl/]\" title=\"[field:title/]\"><img src=\"[field:picname/]\" alt=\"[field:title/]\" title=\"[field:title/]\"> </a>\r\n          <h4 style=\" text-align:center;\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\"></a><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></h4>\r\n        </li>\r\n        ",1791,2161);
$z[8][4]['pagesize']="8";
$z[9]=Array("pagelist","",2234,2293);
$z[9][4]['istitem']="index,pre,next,end,";
$z[9][4]['listsize']="5";
$z[10]=Array("include","",2379,2416);
$z[10][4]['filename']="footer.htm";

?>