<?php
$z[0]=Array("field","",249,268);
$z[0][4]['name']="title";
$z[1]=Array("global","",269,295);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",335,364);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",403,461);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1283,1318);
$z[4][4]['filename']="head.htm";
$z[5]=Array("include","",1520,1555);
$z[5][4]['filename']="left.htm";
$z[6]=Array("field","",1619,1648);
$z[6][4]['name']="position";
$z[7]=Array("field","",1659,1688);
$z[7][4]['name']="typename";
$z[8]=Array("list","\n        <li><a href=\"[field:arcurl/]\" title=\"[field:title/]\"><img src=\"[field:picname/]\" alt=\"[field:title/]\" title=\"[field:title/]\"> </a>\n          <h4 style=\" text-align:center;\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\"></a><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></h4>\n        </li>\n        ",1754,2120);
$z[8][4]['pagesize']="8";
$z[9]=Array("pagelist","",2190,2249);
$z[9][4]['istitem']="index,pre,next,end,";
$z[9][4]['listsize']="5";
$z[10]=Array("include","",2329,2366);
$z[10][4]['filename']="footer.htm";

?>