<?php
$z[0]=Array("field","",253,272);
$z[0][4]['name']="title";
$z[1]=Array("global","",273,299);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1308,1343);
$z[2][4]['filename']="head.htm";
$z[3]=Array("field","",1399,1418);
$z[3][4]['name']="title";
$z[4]=Array("include","",1624,1659);
$z[4][4]['filename']="left.htm";
$z[5]=Array("field","",1725,1754);
$z[5][4]['name']="position";
$z[6]=Array("field","",1765,1794);
$z[6][4]['name']="typename";
$z[7]=Array("list","\r\n        <li><a href=\"[field:arcurl/]\"><img src=\"[field:picname/]\"></a>\r\n          <h4><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></h4>\r\n          <span>文章来源：<b>[field:adminname/]</b> 上传时间：<b>[field:pubdate function=\"GetDateTimeMK(@me)\" /]</b> 阅览次数：<b>[field:click/]</b></span>\r\n          <p>[field:infos/]...<a href=\"[field:arcurl/]\">【详细】</a></p>\r\n        </li>\r\n        ",1863,2329);
$z[7][4]['pagesize']="4";
$z[7][4]['infolen']="180";
$z[8]=Array("pagelist","",2402,2465);
$z[8][4]['listitem']="index,info,next,pageno";
$z[8][4]['listsize']="5";
$z[9]=Array("include","",2553,2590);
$z[9][4]['filename']="footer.htm";

?>